"""Knowledge-base ports (Protocols). Adapters live in infrastructure/.

The ingest use case (K1) uses the mutating side (add/remove); the hybrid retriever (K2)
will use the search side. Persistence (load/save) is an adapter concern, not a port.
"""
from typing import Protocol

from domain.entities import Chunk, DocRecord


class Embedder(Protocol):
    def embed(self, texts: list[str]) -> list[list[float]]: ...


class VectorIndex(Protocol):
    def add(self, ids: list[int], vectors: list[list[float]]) -> None: ...

    def remove(self, ids: list[int]) -> None: ...

    def search(self, vector: list[float], k: int) -> list[tuple[int, float]]: ...


class LexicalIndex(Protocol):
    def add(self, ids: list[int], texts: list[str]) -> None: ...

    def remove(self, ids: list[int]) -> None: ...

    def search(self, query: str, k: int) -> list[tuple[int, float]]: ...


class ChunkStore(Protocol):
    def add(self, chunks: list[Chunk]) -> None: ...

    def remove(self, ids: list[int]) -> None: ...

    def get(self, chunk_id: int) -> Chunk | None: ...

    def all(self) -> list[Chunk]: ...


class Manifest(Protocol):
    def get(self, doc_id: str) -> DocRecord | None: ...

    def doc_ids(self) -> list[str]: ...

    def set(self, doc_id: str, record: DocRecord) -> None: ...

    def delete(self, doc_id: str) -> None: ...

    def allocate_ids(self, count: int) -> list[int]: ...
